version: '3'
services:
  master:
    build:
      context: .
      dockerfile: Docker-master
    ports:
      - 25000:25000
    environment:
      - SECONDARY_URLS=http://secondary1:25001,http://secondary2:25001

  secondary1:
    build:
      context: .
      dockerfile: Docker-secondary
    ports:
      - 25001:25001

  secondary2:
    build:
      context: .
      dockerfile: Docker-secondary
    ports:
      - 25002:25001